name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        run: |
          docker build -t mon_image_vue .
          docker tag mon_image_vue ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/mon_image_vue:latest
          $(aws ecr get-login --no-include-email --region REGION)
          docker push ACCOUNT_ID.dkr.ecr.REGION
