name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        run: |
          docker build -t iris-front_image .
          docker tag iris-front_image 171008152110.dkr.ecr.eu-west-3.amazonaws.com/iris-front_image:latest
          $(aws ecr get-login --no-include-email --region REGION)
          docker push 171008152110.dkr.ecr.eu-west-3
